4darsh-Dev/DecenTrade

Code of Conduct.md

Closes- #4 
@4darsh-Dev Please review my pr under wob'24 and add labels : wob24 and level1

Adding Code of Conduct

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_update.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PR_Template.md

closing issue #7 
@4darsh-Dev please review my PR

Adding Issue-Template and also PR-template

---

frontend/src/components/Navbar.jsx

Navbar logo clickable

---

frontend/src/App.jsx
frontend/src/components/NFTMarketplace.jsx
frontend/src/components/Navbar.css
frontend/src/components/Navbar.jsx
frontend/src/pages/HomePage.jsx

updated the Navbar to have the Connect Wallet option

---

frontend/src/components/Navbar.css
frontend/src/components/Navbar.jsx
frontend/src/pages/CreateNFTPage.jsx

Added toggle button at navbar to light-to dark mode

Added toggle button for light-dark button

---

frontend/src/pages/CreateNFTPage.jsx

[BUG]: Create NFT Form UI Is Inconsistent #52
This pull request addresses the inconsistency in the UI of the Create NFT form compared to the rest of the website. The changes made ensure that the form's design aligns with the overall theme of the site, including adjustments to button styles and layout to create a cohesive user experience.
https://github.com/user-attachments/assets/b37ee406-9579-411a-957e-808924c13d9c
The updates enhance the user experience by providing a visually consistent design across the site, making the Create NFT form feel integrated rather than disjointed.
@4darsh-Dev , Please add label of hactoberfest-accepted too.

Aligned Create NFT Form UI with Website Theme

---

backend/app.js
backend/package-lock.json
backend/package.json
backend/vercel.json
frontend/src/utils/ethereum.js

1. added vercel.json for backend API deployment
2. added cors * all for now  -- to be changed later
3. updated frontend/ethereum.js for routes 
4. Tested whole setup locally with pinata

Backend + Frontend Ingtegeration

---

frontend/src/components/InfoCards.jsx

fix: #48 
**After:**
**Before**
Hey @4darsh-Dev please review my PR.

Improve card design

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/AboutPage.jsx
frontend/src/pages/CreatorsPage.jsx
frontend/src/pages/FAQPage.jsx
frontend/src/pages/HomePage.jsx

This PR addresses the issue of a missing footer across multiple pages in the application. It adds a consistent footer to all relevant pages and enhances its responsiveness to improve user experience on both desktop and mobile devices.
- Closes : #98 
- **Footer Component Added**: Integrated the footer component into the following pages:
- [List the pages where the footer was added, e.g., Home, About, Contact, etc.]
- **Responsiveness Improvements**: 
- The footer is now fully responsive, with a layout that adapts to different screen sizes.
- The subscribe section has been adjusted to stack vertically on mobile devices while maintaining a side-by-side layout on desktop.
- Used Tailwind CSS for styling to ensure a clean and modern look.
**Screenshots:**
- Desktop
- Mobile

Missing Footer on Multiple Pages and Responsiveness Improvements

---

Code of Conduct.md

Fixes issue #115 
As per the issue #115  I update the file with all require changes
I updated the code of conduct file by making changes in following points -
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion
Also , I tried to make ik more interative.
If any further changes required please tell me.

Updated Code of Conduct.md

---

frontend/src/components/Navbar.css
frontend/src/components/Navbar.jsx

fix: #49 
**Desktop**
**Mobile** 
hey @4darsh-Dev please review my PR

ADD Sticky navbar, made it responsive added Hamber DD when on mobile view

---

frontend/src/pages/ExplorePage.jsx

This PR adds error handling to the **Explore** page to account for scenarios where the user has not connected their wallet. Previously, users without a connected wallet would experience issues when trying to explore content, resulting in continuous loading.
1. **Error Display on Explore Page**:
- Added a condition to check if the user has a connected wallet. If not, an error message is displayed, informing the user that wallet connection is required to explore the content.
2. **Redirect Logic**:
- If the user attempts to access the Explore page without a wallet connection, they will be redirected to the wallet connection page.
- Before:
- After (with error handling):
- Closes #96 
---

Added Error Handling for Missing Wallet Connection on Explore Page

---

.github/workflows/pr_checker.yaml

Closes #102 
**Usage:**
1. When a pull request is created or edited, the workflow automatically triggers.
2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes , Close, Closes, Closed , Fix , Fixed , Resolve , Resolves #Issue_number`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.
**_Note_**: Kindly add all the labels added to the issue #102 , to this PR! and assign me!
@4darsh-Dev

Implement GitHub PR Issue Checker Workflow

---

frontend/src/components/Navbar.jsx
frontend/src/pages/CreatorsPage.jsx
frontend/src/pages/FAQPage.jsx
frontend/src/styles/faq.css
frontend/tailwind.config.js

Changed the hard coded dark mode toggle feature with tailwindcss dark mode feature and improve white color texts in dark mode and enhance overall ui.
fixes #104

Imporove Dark mode effects and ui

---

smart-contracts/scripts/deploy.js

Added await nftContract.deployed() and await marketplaceContract.deployed() to ensure that the contracts are fully deployed before proceeding. Gas Cost Logging: Uncommented the relevant logging to show gas usage and transaction costs.

Update DecenTrade deploy.js

---

backend/app.js
backend/package-lock.json
backend/package.json
backend/src/controllers/nftController.js
backend/src/routes/nfts.js
backend/src/services/pinataService.js
backend/src/utils/getContract.js
backend/src/utils/toBase64.js
frontend/package-lock.json
frontend/package.json
frontend/src/main.jsx
frontend/src/pages/ExplorePage.jsx
frontend/src/utils/ethereum.js
frontend/src/utils/handleCompressedData.js

Fixes issue #105 
1. Users need to connect wallet to view nfts in exploreNft page.
2. Fetching nfts through pinata gateway from frontend is not secure.
1. Used Infura provider instead of wallet to get wallet to fetch data from smart contracts.
2. Moved nft fetching logic from frontend to backend by making an api
1. loadNfts functions runs when explorePage mounts without needing to connect wallet.
2. User need to connect wallet when buying an nft.
3. Added route in the backend to handle fetchNfts request.
4. Interaction with blockchain and IPFS from the backend.
5. Compressed images using Pako library and send to the frontend.
I have tested the api and its working with a harcoded metadata cid and image cid for fetching data from IPFS as I don't have access to the admin's IPFS. 
1. Please …

Fixes issue #105 : Users can view nfts without connecting wallet 

---

frontend/index.html
frontend/src/App.jsx
frontend/src/components/GTranslateLoader.js

closes #132 
please review this pr. Thanks! @4darsh-Dev

added multilanguage support

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/main.jsx
frontend/src/pages/CreatorsPage.jsx

added react count up animation to the creators page 
video:
https://drive.google.com/file/d/1BEKtvUXLzjdigSrOhQtRc5rTBS2Ig-rm/view?usp=sharing

added count up animation

---

frontend/src/pages/FAQPage.jsx

fix #129 
Please View Video for a Better understanding of the Changes
https://github.com/user-attachments/assets/5796a6eb-003f-444a-b671-f5e46996859e

Enhance FAQS Section and Added Forums | Issue #129

---

frontend/src/components/InfoCards.jsx

@4darsh-Dev  @panwar8279  Please merge this pr by adding appropriate labels under Hacktoberfest'24.
Here,is attached video for reference of changes I did-
https://github.com/user-attachments/assets/9f64771d-093b-4494-bdfb-b939def91640

Resolve issue [Bug]: Not taking to  correct pages #135

---

frontend/src/components/Footer.jsx

added confirmation message after subscribing the newsletter form

---

frontend/src/components/Navbar.jsx

add cross icon to close navbar if it is open 
#124 
@panwar8279 
[decen.webm](https://github.com/user-attachments/assets/7120ce94-91d5-4eb8-be5c-d57b2ac7bb0a)

fixes #124: mobile view navbar - add cross icon

---

frontend/index.html
frontend/src/components/InfoCards.jsx

Styling adjustments:
* [`frontend/src/components/InfoCards.jsx`](diffhunk://#diff-17b051eb1f6da035e014955f65a5e32e21b635b6db3dd529dd0c212e9db2d25aL50-R50): Added a `pb-12` (padding-bottom) class to the `div` containing the info cards to improve spacing.
https://github.com/user-attachments/assets/9f011ec8-92a4-46ec-96a8-d9e9f72fc1f2

[FIX] Hover Effect of Footer Upper Section Card

---

improve home page

Create improve home page

---

frontend/index.html
frontend/src/App.jsx
frontend/src/components/ScrollToTop.jsx
frontend/src/styles/ScrollToTop.css

Solved :
Issue no #168 
On scroll at button right corner Scroll to top button appears with animation and matching color to website.
https://github.com/user-attachments/assets/d69d7304-ece9-4b51-91cf-084533c16824

Added Animated Scroll to top button

---

backend/dockerfile
docker-compose.yml
frontend/dockerfile

fixes #161 
added docker file for both frontend and backend also added docker compose file for entire project
please accept this pr under gssoc-ext minimum level 2

added dockerfile and docker-compose

---

.github/ISSUE_TEMPLATE/custom.yml

Creating a custom issue template for the project can significantly enhance the process of issue reporting and tracking. Here’s why it is necessary and some key components to include in your custom issue template:
- **Consistency**: A custom template ensures that all issues follow a consistent format, making it easier for contributors and maintainers to understand and categorize them.
- **Clarity**: It helps guide users to provide all necessary information, reducing back-and-forth communication for missing details.
- **Efficiency**: Streamlining the issue creation process helps contributors focus on the problem rather than figuring out what information is needed.
1. **Title**: A brief summary of the issue.
2. **Description**: A detailed explanation of the issue, including steps to …

CREATE CUSTOM ISSUE TEMPLATE

---

README.md

Add Stargazers and Forkers Profiles to README.md ✨

---

frontend/src/components/VoiceInput.jsx
frontend/src/pages/ChatPage.jsx

1. Fixed speech to text error by removing speechly services
2. Currently using Gradio app that uses whisper base model for this purpose.

Voice Input Completed
